website_django307/apps/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "accounts"
urlpatterns = [
    path("profile", views.ProfileView.as_view(), name="profile"),
    # django auth
    path(
        "login",
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
    path("logout", auth_views.LogoutView.as_view(), name="logout"),
]

website_django307/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("website_django307.apps.public.urls")),
    path("accounts/", include("website_django307.apps.accounts.urls")),
]

website_django307/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserInterest(models.Model):
    name = models.CharField(max_length=64, unique=True)
    normalized_name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.name


class UserPersona(models.Model):
    name = models.CharField(max_length=64, unique=True)
    normalized_name = models.CharField(max_length=64, unique=True)
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class UserProfile(models.Model):
    # owner
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    is_full_name_displayed = models.BooleanField(default=True)
    # details
    bio = models.CharField(max_length=500, blank=True, null=True)
    website = models.URLField(max_length=200, blank=True, null=True)
    persona = models.ForeignKey(
        UserPersona, on_delete=models.SET_NULL, blank=True, null=True
    )
    interests = models.ManyToManyField(UserInterest, blank=True)

website_django307/apps/accounts/views.py
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = "accounts/profile.html"

website_django307/templates/about.html
{% extends 'base.html'%}

{% block title %}About{% endblock %}

{% block content %}
<h1>
    About
</h1>
{% endblock %}

website_django307/templates/accounts/login.html
{% extends 'base.html'%}

{% block title %}Login{% endblock %}

{% block content %}
<h2>Login</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
</form>
{% endblock %}

website_django307/templates/accounts/profile.html
{% extends 'base.html'%}

{% block title %}Profile{% endblock %}

{% block content %}
<h1>
    {{ user.get_full_name }}'s (@{{user.username}})
</h1>

{% with profile=user.profile %}
    {% if profile %}
        <h2>
            {{ profile.persona|default:"" }}
        </h2>
        <div>
            {{ profile.bio|default:"" }}
        </div>
        <div>
            {% with website=profile.website|default:"" %}
                <a href="{{website}}">{{ website }}</a>
            {% endwith %}
        </div>
        <br/>
        <div>
            Interests:
            {% for interest in profile.interests.all %}
                <span>
                    {{ interest.name }}{% if not forloop.last %}, {% endif %}
                </span>
            {% endfor %}
        </div>
    {% endif %}

{% endwith %}
{% endblock %}

website_django307/templates/base.html
{% load static %}

<!-- templates/base.html-->
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Welcome{% endblock %}</title>

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Freelancer - Start Bootstrap Theme</title>
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'theme/css/styles.css' %}" rel="stylesheet" />
        <link href="{% static 'css/main.css' %}" rel="stylesheet" />


</head>
<body>
{% include 'navbar.html' %}
    <main id="main">
        {% block content %}
        {% endblock %}
    </main>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'theme/js/scripts.js' %}"></script>
</body>

</html>

website_django307/templates/contact.html
{% extends 'base.html'%}

{% block title %}Contact{% endblock %}

{% block content %}
<h1>
    Contact
</h1>
{% endblock %}

website_django307/templates/index.html
{% extends 'base.html'%}
{% load static %}

{% block title %}Welcome{% endblock %}

{% block content %}
 <!-- Masthead-->
        <header class="masthead text-white text-center">
            <div class="container d-flex align-items-center flex-column">
                <!-- Masthead Avatar Image-->
                <img class="masthead-avatar mb-5" src="{% static 'img/avataaars.svg' %}" alt="" />
                <!-- Masthead Heading-->
                <h1 class="masthead-heading text-uppercase mb-0">Welcome!</h1>
        </header>
<h1>
    Template Homepage
</h1>
{% endblock %}

website_django307/templates/navbar.html
{% url 'public:index' as index_url %}
{% url 'public:about' as about_url %}
{% url 'public:contact' as contact_url %}

<nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="{{ index_url }}">Derick-Louie Trinidad</a>
        <button class="navbar-toggler text-uppercase font-weight-bold dt-bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav mx-auto">
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 js-scroll-trigger {% if request.path == index_url %}active{% endif %}" href="{{ index_url }}">Home</a></li>
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 js-scroll-trigger {% if request.path == about_url %}active{% endif %}" href="{{ about_url }}">About</a></li>
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 js-scroll-trigger {% if request.path == contact_url %}active{% endif %}" href="{{ contact_url }}">Contact</a></li>
            </ul>
        </div>
    </div>
</nav>


<!--<nav>-->
<!--    {% url 'public:index' as index_url %}-->
<!--    <span>{% if request.path == index_url %}Home{% else %}<a href="{{ index_url }}">Home</a>{% endif %}</span>-->
<!--    {% url 'public:about' as about_url %}-->
<!--    <span>{% if request.path == about_url %}About{% else %}<a href="{{ about_url }}">About</a>{% endif %}</span>-->
<!--    {% url 'public:contact' as contact_url %}-->
<!--    <span>{% if request.path == contact_url %}Contact{% else %}<a href="{{ contact_url }}">Contact</a>{% endif %}</span>-->
<!--    <span style="float:right">-->
<!--        {% if user.is_authenticated %}-->
<!--            {% url 'accounts:profile' as profile_url %}-->
<!--            <span>Hi {% if request.path == profile_url %}{{ user.username }}{% else %}<a href="{{ profile_url }}">{{ user.username }}</a>{% endif %}</span>-->
<!--            <span><a href="{% url 'accounts:logout' %}">Logout</a></span>-->
<!--        {% else %}-->
<!--            <span><a href="{% url 'accounts:login' %}">Login</a></span>-->
<!--        {% endif %}-->
<!--    </span>-->
<!--</nav>-->